
bash ./plink_clump.sh 1 \
bash ./plink_clump.sh 2 \
bash ./plink_clump.sh 3 \
bash ./plink_clump.sh 4 \
bash ./plink_clump.sh 5 \
bash ./plink_clump.sh 6 \
bash ./plink_clump.sh 7 \
bash ./plink_clump.sh 8 \
bash ./plink_clump.sh 9 \
bash ./plink_clump.sh 10 \
bash ./plink_clump.sh 11 \
bash ./plink_clump.sh 12 \
bash ./plink_clump.sh 13 \
bash ./plink_clump.sh 14 \
bash ./plink_clump.sh 15 \
bash ./plink_clump.sh 16 \
bash ./plink_clump.sh 17 \
bash ./plink_clump.sh 18 \
bash ./plink_clump.sh 19 \
bash ./plink_clump.sh 20 \
bash ./plink_clump.sh 21 \
bash ./plink_clump.sh 22 \