
bash ./plink_clump_newdata.sh 1 \
bash ./plink_clump_newdata.sh 2 \
bash ./plink_clump_newdata.sh 3 \
bash ./plink_clump_newdata.sh 4 \
bash ./plink_clump_newdata.sh 5 \
bash ./plink_clump_newdata.sh 6 \
bash ./plink_clump_newdata.sh 7 \
bash ./plink_clump_newdata.sh 8 \
bash ./plink_clump_newdata.sh 9 \
bash ./plink_clump_newdata.sh 10 \
bash ./plink_clump_newdata.sh 11 \
bash ./plink_clump_newdata.sh 12 \
bash ./plink_clump_newdata.sh 13 \
bash ./plink_clump_newdata.sh 14 \
bash ./plink_clump_newdata.sh 15 \
bash ./plink_clump_newdata.sh 16 \
bash ./plink_clump_newdata.sh 17 \
bash ./plink_clump_newdata.sh 18 \
bash ./plink_clump_newdata.sh 19 \
bash ./plink_clump_newdata.sh 20 \
bash ./plink_clump_newdata.sh 21 \
bash ./plink_clump_newdata.sh 22 \